import React from "react";

export default function Product() {
  return [
    {
      id: 1,
      nombre: "Bikini tokio",
      precio: "1900",
      imagen: "",
      categoria: "bikini",
    },
    {
      id: 2,
      nombre: "Bikini milan",
      precio: "1900",
      imagen: "image/Imagen de WhatsApp 2022-12-20 a las 51.jpg",
      categoria: "bikini",
    },
    {
      id: 3,
      nombre: "Bikini paris ",
      precio: "1900",
      imagen: "image/Imagen de WhatsApp 2022-12-20 a las 17.jpg",
      categoria: "bikini",
    },
    {
      id: 4,
      nombre: "Bikini texas",
      precio: "1900",
      imagen: "image/Imagen de WhatsApp 2022-12-20 a las 51.jpg",
      categoria: "bikini",
    },
    {
      id: 5,
      nombre: "Bikini mariposa",
      precio: "1900",
      imagen: "image/Imagen de WhatsApp 2022-12-20 a las 53.jpg",
      categoria: "bikini",
    },
    {
      id: 6,
      nombre: "  Vedetina estampada",
      precio: "1900",
      imagen: "image/vedetinaestampada.jpg",
      categoria: "lenceria",
    },
    {
      id: 7,
      nombre: "Conjunto tazasoft",
      precio: "1900",
      imagen: "image/conjuntotaza.jpg",
      categoria: "lenceria",
    },
    {
      id: 8,
      nombre: "Boxer calvin klein",
      precio: "$1900",
      imagen: "image/boxers.jpg",
      categoria: "hombre",
    },
    {
      id: 9,
      nombre: "Soquetes",
      precio: "1900",
      imagen: "image/soquetehombre.jpg",
      categoria: "hombre",
    },
    {
      id: 10,
      nombre: "Vedetina rallada",
      precio: "1900",
      imagen: "image/vedetinaralladajpg.jpg",
      categoria: "lenceria",
    },
    {
      id: 11,
      nombre: "Conjunto triangulo",
      precio: "1900",
      imagen: "image/conjuntotriangulo.jpg",
      categoria: "lenceria",
    },
    {
      id: 12,
      nombre: "Medias caña alta",
      precio: "1900",
      imagen: "image/mediaslarfas.jpg",
      categoria: "hombre",
    },
    {
      id: 13,
      nombre: "conjunto encaje",
      precio: "$1900",
      imagen: "image/conjuntoroja.jpg",
      categoria: "lenceria",
    },
    {
      id: 14,
      nombre: "boxer 2",
      precio: "$1900",
      imagen: "image/boxerrr.jpg",
      categoria: "hombre",
    },
    {
      id: 15,
      nombre: "Bombacha nena",
      precio: "1900",
      imagen: "image/bombachanena.jpg",
      categoria: "ninios",
    },
    {
      id: 16,
      nombre: "Pijama bob esponja",
      precio: "3100",
      imagen: "image/piyamabob.jpg",
      categoria: "ninios",
    },
    {
      id: 16,
      nombre: "Pijama mickey",
      precio: "$3100",
      imagen: "image/piyamamickey.jpg",
      categoria: "ninios",
    },
    {
      id: 17,
      nombre: "  medias niños",
      precio: "1500",
      imagen: "image/mediasniño.jpg",
      categoria: "ninios",
    },
  ];
}
